---
- name: Install Apache on RedHat
  gather_facts: false
  hosts: amazonservers
  become: true

  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present


- name: Install Apache on Ubuntu
  gather_facts: false
  hosts: ubuntuservers
  become: true

  tasks:
    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present